### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by asterd**
- specify bar height
- specify custom box decoration of bar
- specify custom textStyle
- specify custom text fontSize
- fix bug in preselection of different index. I can explain better if required

### CODE REVIEW

**Comment by watery-desert** [comment]
Thanks for addressing the bug and fixing it. 

About the features, it's not looking good in your PR. They aren't aligned. I might allow fontWeight, fontSize. Consider submitting with bug and fontWeight, fontSize. 

Screenshot 2021-07-27 at 09 42 47

**Comment by asterd** [comment]
Hi,
sorry If I insist, why did you say "they aren't aligned?". 
The intention of this PR is to provide multiple way to customize the UI of the bottom bar, even in case of customized approaches. For example, in my app (where I use the customization) I have a custom font for all the bottom bars (a font that is different from the Theme base one) and has some other customization (like italic or other). So, the logic behind is: if you want the standard structure, you can customize only the fontSize since you can customize the bar height. But if you want something very custom, you can change all the fontStyle. In the same way, you can customize also the borders of the bottom bar and so on. Anyway, the package is yours and mine is only a proposal. If you think I have to remove the TextStyle customization in favour of only size and weight customization, I'll do it asap. 
Let me know please!

**Comment by watery-desert** [comment]
I am sick since Saturday. So I tried to reply to you in short. Hopefully, you understand. 

I can give more customization options. When I run the PR it doesn't look the same as the original design. What it should look exactly like this https://dribbble.com/shots/5605168-Toolbar-icons-animation out of the box. 

About the BoxDecoration, if you change a lot things will look ugly, but I think developers might need some options like drop shadow, rounded corner, etc of the bar. Nobody has asked for yet, so I didn't include. 

Yeah, developers might need to change some textStyle but I don't think all of them. Can you share a screenshot with me your texts.

**Comment by asterd** [comment]
I've updated the code to be original-design compliant.

my ui look like this: 

[https://ibb.co/xGW1NJ1](url)

and my code looks like:

```
body: TabBarView(
        controller: controller.tabController,
        physics: const NeverScrollableScrollPhysics(),
        children: <Widget>[
          generalInfo(),
          Obx(aeInfo),
          OutlookContactsPage(),
        ],
      ),
      bottomNavigationBar: Obx(() => SlidingClippedNavBar(
        onButtonPressed: (index) {
          controller.changeTabIndex(index);
        },
        barDecoration: const BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.grey,
              offset: Offset(0, 1), //(x,y)
              blurRadius: 3,
            ),
          ],
        ),
        barHeight: 80,
        textStyle: ThemeUtils.boldText().copyWith(fontSize: 15, fontFamily: 'Roboto'),
        activeColor: ThemeUtils.primaryColor(),
        selectedIndex: controller.tabIndex,
        barItems: [
          BarItem(
            icon: Icons.info_outline,
            title: 'cinfo.menu.info'.tr,
          ),
          BarItem(
            icon: Icons.qr_code_rounded,
            title: 'cinfo.menu.ae'.tr,
          ),
          BarItem(
            icon: Icons.contacts_outlined,
            title: 'cinfo.menu.contacts'.tr,
          ),
        ],
      )),
```

**Comment by watery-desert** [comment]
Your link is not working. 

1. Bar height should be 100 always. When I was developing the package I found 100 is the sweet spot according to the original design. However, I will try to refactor and see if it's possible somehow manage. any value less than 100 making the bar too tight visually. I also mentioned in doc that `Keep that in mind this navigation menu is taller than normal for small screen it might cover more screen real estate.`

2. I will make some API for border radius, drop shadow. I saw you change `BoxDecoration` `color` in your code I can't figure out what that might look like Since the custom painter needs to be the same as the bar color. If you want you can add these two APIs.

3. And you don't need to depend on any API for that you can apply your own TextStyle to any specific widget from outside. Here I did that without Changing Anything from the Package. 

Screenshot 2021-07-27 at 15 32 15

Update the PR with bug fix and (optionally add border radius, drop shadow these two APIs if you can).

**Comment by asterd** [comment]
Ok, before doing some editing to my code, I'll try to share with you some ideas:
1. I understand that barHeight of 100 is the perfect size to replicate the original design, but (as you already mentioned in docs) it looks unusable on small-screen devices (it is too high) but, with the ability to set a custom bar height (as in my PR), you can set a different height based on different screen size and I assure you that it looks very good. So, I want to know if I can maintain this modification with a doc update that warn that, in case you change the bar height, the design can vary in a way that we can't manage and is something that the end user must know or you don't want to provide this ability. Take in mind that I've tried with many different values in a range between 60 and 100 and in each case it looks very good.
2. I can add dropShadow and borderRadious to the api, but I want to know how did you prefer: I can define dropShadow as an array of BoxShadow (exacly as the boxShadow property of boxDecoration) or do you want the end user can only set the y offset of a single boxShadow? and for borderRadious? without border property has little sense. This is the problem to set only a little set of property. In my mind, the boxDecoration property, open to the end user, the ability to customize the look & feel of the external container (with border, shadows and so on). It's obvious that changing these values can alterate the original design, but why do we have to prevent this opportunity. A normal programmer tests the code and the design and understands if there is something wrong. But limiting the customization (in my opinion) is always a bad approach. I guarantee a design if you use the default settings. In any other case is up to you. What can i do is to override (as I'll already do with textcolor) the background color of custom boxDecoration if you define also the backgroundColor property. In my idea, the boxDecoration and textStyle props, are available only for extreme customization and must be used carefully otherwise the package doesn't guarantee the design.
3. for textStyle is the same thing. I see that you have customized the style without touching the API (can you explain how?). Maybe you have changed something at the theme level. But my need is to have something really custom. I know that you can act at theme level, and this is 99% of the cases, but If you want to apply a custom style only for the bar, why can't you do that?

Anyway. the package is yours. These are only my opinions. If you don't want to provide these abilities, I can try to create a PR only with bug-fix and very few additional props that you want to add. Personally, I'll continue to use my customization since enable me to customize the bar in a much more satisfying way.

Let me know please, and thanks a lot for the beautiful work

**Comment by watery-desert** [comment]
1. Here are few challenges I see when the height is less than 100, although 100 - 90 is okay. 

when height is 60 notice there are dots below inactive icons. Also the animation is nowhere same as the original. 
Screenshot 2021-07-28 at 21 30 17

when the height is 70 the upper portation starts to clip. 
Screenshot 2021-07-28 at 21 54 23

I knew this will be an issue when I made this package. I was also thinking 100 is too much. Bottom navigation bar height normally 56, but the animation is moving vertically. I couldn't change much. If you look the code ` SlicedCard.draw` you will notice it's just a custom painter responsible for covering the icon, they aren't actually clipping but rather getting covered. So here is another problem changing bar height meaning also have to adjust the rectangular width and height which is by itself variable when animating, one side of the rectangular height is changing. There is a lot to do, so I decided not give bar height change option. I am not even considering iconsize different icon pack has different default icon miniman size to look normal. So no point to giving the option which will have to be between 100 - 90

2. Here is the reason why I think changing `BoxDecoration` option is bad idea. I am going to expalin all `BoxDecoration` APIs. 
 `backgroundBlendMode` I don't think nobody ever use`BlendMode` here.

**Comment by watery-desert** [comment]
3. No I didn't use app theme, There is a widget for that `DefaultTextStyle` I used it.

finally since you are going to use your forked version then just submit PR with bug fix, and with these two options `roundedCorner`, `shadow` List<BoxShadow> (if you want)

**Pull request closed without merging**
